### ISSUE TITLE
Broken links due to punctuation

### ISSUE THREAD

**Issue by lolmaus** [dohliam/tocdown#1]
Hi! Thank you for this amazing webapp, it's an indispensable tool for me.

I'm seeing some TOC items receive broken links. Consider this source markdown:

```md
# Hi, @dohliam!
```
Here's how GitHub renders it. Note the id:

```html
<h1 id="hi-dohliam">Hi, @dohliam!</h1>
```

Here's how this header should be targeted from a TOC:

```md
* [Hi, @dohliam!](#hi-dohliam)
```
Here's how tocdown renders it, producing a broken link:

```md
* [Hi, @dohliam!](#hi,-@dohliam!)
```

**Comment by lolmaus** [comment]
Uhm, that's not how GitHub actually renders it, but the anchor in my example is identical to GitHub's.

**Comment by dohliam** [comment]
Whoops, I didn't notice you had already submitted a PR for this, and it looks like a better fix! I'll see if I can merge it

**Comment by dohliam** [comment]
Hmm... after some testing I realized that this fixes most problems, but breaks Unicode links (e.g. for non-ASCII characters). [Here](https://github.com/kfcd/pheng-im#轉寫方式一覽) is an example of how non-ASCII links render in Github-flavoured markdown (you might have to hover over the anchor link icon to see the non-escaped version of the link).

I was originally going to go with the regex used by [marked](https://github.com/chjj/marked/blob/master/lib/marked.js), which seems simple enough: `/[^\w:]/`, but this also breaks with non-ASCII.

It looks like there may not be an elegant way of doing this without testing to see which punctuation specifically is removed by Github (or other flavours of markdown). I'm also not sure how Unicode punctuation (curly quotes and em-dashes etc.) are handled. I'll add some of these (as well as your example above) to the [test file](https://github.com/dohliam/tocdown/blob/master/test.md) and we can go from there.

If there were a range of characters that captured approximately `!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~` that would be ideal, but unfortunately I don't think it will be that easy!

**Comment by dohliam** [comment]
I've added some punctuation tests in the file `test.md`, and at least some of the results are a bit surprising. For example, in [this link](https://github.com/dohliam/tocdown/blob/master/test.md#standard-ascii-punctuation--_), the underscore is *not* removed as I would have expected. So a marked.js style `[^\W]` is going to break links as well.

I'm happy to check out an updated PR if you have any ideas!
